name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello 🚀 Future Astronaut , Thank You for Raising An Issue 💀 !!! , ill look into it asap 😅"
        pr-message: "Whoa there Astronaut 🚀, Thank you  for Your First PR"
